### ISSUE TITLE
Not working in QGIS 2.18.9

### ISSUE THREAD

**Issue by Sidapo** [pjgeng/Contour-Labels#2]
First of all thank you for this great tool! I am trying to get the script to run in QGIS 2.18.9. I am trying it out on the test data provided.
The script stops with this error message:
```
'NoneType' object has no attribute '__getitem__' See log for more details
```
and in the log:
```
2017-07-05T19:44:58	1	Error: Wrong number of parameters
2017-07-05T19:44:58	2	Uncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 378, in processAlgorithm
			    exec((script), ns)
			  File "<string>", line 47, in <module>
			TypeError: 'NoneType' object has no attribute '__getitem__'
			
2017-07-05T19:46:56	1	Error: Wrong number of parameters
2017-07-05T19:46:56	2	Uncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 378, in processAlgorithm
			    exec((script), ns)
			  File "<string>", line 47, in <module>
			TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pjgeng** [comment]
Cheers for the feedback. As per Readme the script is currently only designed and tested against 2.14.8 LTE or 2.16.1. It appears 2.18 has (once again) changed the number of inputs for some of the geoprocessing operations. In this case the culprit appears to be the qgis:intersection in line 45 which returns invalid output which then is passed through the field calculator on line 46 to eventually error down the line on line 47.

While an update to 2.18 is on the cards it also appears that different versions of 2.18 behave differently in this case. I will likely update to the last release of the 2.18 series once 3.0 is release in Q4 2017. Along with an update to 3.0 which will likely involve a new script.

**Comment by Sidapo** [comment]
Thanks for getting back to me! Somehow I'm still not able to get the script to work on versions 2.14.8 or 2.16.1. I basically get the same error on 2.14.8:
```
2017-08-22T13:21:24	1	Fehler: Falsche Parameteranzahl
2017-08-22T13:21:24	2	Uncaught error while executing algorithm
			Traceback (most recent call last):
			  File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing\core\GeoAlgorithm.py", line 203, in execute
			    self.processAlgorithm(progress)
			  File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing\script\ScriptAlgorithm.py", line 323, in processAlgorithm
			    exec((script), ns)
			  File "<string>", line 175, in <module>
			TypeError: 'NoneType' object has no attribute '__getitem__'
```
I guess I'll just wait for v 3.0 or try to intersect the contours manually..
Cheers!
